#!/bin/sh
flags=""
case "$@" in
*--*)
	for arg
	do
		shift
		case "$arg" in
		--) break;;
		*) flags="$flags $arg";;
		esac
	done;;
esac
for srcfile
do
	/usr/bin/cpp -M -W -Wall -Wformat=2 -Wshadow $flags $srcfile 2>/dev/null
done
exit 0
